server:
  port: ${SERVER_PORT:8083}

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: com.bluesalt.bluesaltpay.billingworkerservice.config.TransactionDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: "*"

spring:
  sql:
    init:
      platform: mysql

  datasource.url: ${DATASOURCE_URL}
  datasource.username: ${DATASOURCE_USERNAME}
  datasource.password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}